language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make test_cov
  - make test_xunit
  - make lint
  - make docker_build
  
after_success:
  - make docker_push

deploy:
  provider: heroku
  app: sheltered-fortress-98737
  api_key: ${HEROKU_API_KEY}
